#ifndef CONSTRAINT_HPP
#define CONSTRAINT_HPP

#define NBR_SHIP_BULLET 4
#define NBR_ENEMY_BULLET 8
#define NBR_ENEMY 13

#define DAMAGED_DURATION 20
#define DAMAGED_TICK_INTERVAL 4
#define EXPLODE_DURATION 40

#define SHIP_LIVES 5
#define SHIP_SPEED 1
#define SHIP_BULLET_SPEED 4
#define SHIP_BULLET_DURATION 320 / SHIP_BULLET_SPEED
#define SHIP_BULLET_INTERVAL (SHIP_BULLET_DURATION / NBR_SHIP_BULLET)

#define BOSS_POINT 500
#define BOSS_HEALTH 100
#define BOSS_MOVE_DURATION 250
#define BOSS_BULLET0_DURATION 300
#define BOSS_BULLET0_INTERVAL 800
#define BOSS_BULLET1_DURATION 250
#define BOSS_BULLET1_INTERVAL 600

#define ENEMY1_POINT 50
#define ENEMY1_HEALTH 2
#define ENEMY1_MOVE_DURATION  40
#define ENEMY1_BULLET_DURATION 50
#define ENEMY1_BULLET_INTERVAL 50

#define ENEMY0_POINT 20
#define ENEMY0_HEALTH 4
#define ENEMY0_MOVE_DURATION 100

#define ENEMY_GAP 24
#define ENEMY_LINE0 35
#define ENEMY_LINE1 ENEMY_LINE0 + 30
#define ENEMY_LINE2 ENEMY_LINE1 + 30
#define ENEMY_LINE3 ENEMY_LINE2 + 40
#define ENEMY_LINE4 ENEMY_LINE3 + 40

#endif /* CONSTRAINT_HPP */
